=== AutomatedProcessImprovement/knockouts-optimization/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "log_path": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "redesign_results_file_path": {
      "type": "string"
    },
    "cache_dir": {
      "type": "string"
    },
    "start_activity": {
      "type": "string"
    },
    "end_activity": {
      "type": "string"
    },
    "post_knockout_activities": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "success_activities": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "known_ko_activities": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "exclude_from_ko_activities": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "attributes_to_ignore": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "rule_discovery_algorithm": {
      "type": "string"
    },
    "confidence_threshold": {
      "type": "number"
    },
    "support_threshold": {
      "type": "number"
    },
    "max_rules": {
      "type": "integer"
    },
    "k": {
      "type": "integer"
    },
    "n_discretize_bins": {
      "type": "integer"
    },
    "dl_allowance": {
      "type": "integer"
    },
    "prune_size": {
      "type": "number"
    },
    "always_force_recompute": {
      "type": "boolean",
      "default": true
    },
    "ignore_log_parsing_cache": {
      "type": "boolean",
      "default": false
    },
    "print_rule_discovery_stats": {
      "type": "boolean",
      "default": false
    },
    "grid_search": {
      "type": "boolean",
      "default": false
    },
    "param_grid": {
      "type": "object",
      "properties": {
        "k": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            }
          ]
        },
        "n_discretize_bins": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            }
          ]
        },
        "dl_allowance": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            }
          ]
        },
        "prune_size": {
          "type": "array",
          "items": [
            {
              "type": "number"
            }
          ]
        }
      }
    },
    "read_options": {
      "type": "object",
      "properties": {
        "column_names": {
          "type": "object",
          "properties": {
            "Activity": {
              "type": "string"
            },
            "Case ID": {
              "type": "string"
            },
            "Resource": {
              "type": "string"
            },
            "lifecycle:transition": {
              "type": "string"
            }
          },
          "required": [
            "Activity",
            "Case ID",
            "Resource",
            "lifecycle:transition"
          ]
        },
        "one_timestamp": {
          "type": "boolean"
        }
      }
    },
    "skip_temporal_holdout": {
      "type": "boolean",
      "default": false
    }
  },
  "required": [
    "log_path",
    "output",
    "redesign_results_file_path",
    "cache_dir"
  ]
}

=== AutomatedProcessImprovement/knockouts-optimization/knockout_ios/config/bpi_2013.json
{
  "log_path": "inputs/BPI_Challenge_2013_incidents.xes",
  "output": "./outputs",
  "redesign_results_file_path": "outputs/bpi_2013.txt",
  "cache_dir": "cache/bpi_2013",
  "start_activity": "A_Create Application",
  "post_knockout_activities": [
    "A_Denied"
  ],
  "success_activities": [],
  "known_ko_activities": [],
  "exclude_from_ko_activities": [
    "End"
  ],
  "attributes_to_ignore": [
  ],
  "rule_discovery_algorithm": "RIPPER",
  "confidence_threshold": 0.5,
  "support_threshold": 0.1,
  "max_rules": 3,
  "k": 2,
  "n_discretize_bins": 20,
  "dl_allowance": 1,
  "prune_size": 0.5,
  "always_force_recompute": true,
  "print_rule_discovery_stats": true,
  "grid_search": false
}

=== AutomatedProcessImprovement/knockouts-optimization/knockout_ios/test/config/envpermit_auto.json
{
  "$schema": "../../../config_schema.json",
  "log_path": "test/inputs/Envpermit_complete_cases.xes",
  "output": "test/outputs",
  "redesign_results_file_path": "test/outputs/envpermit_auto.txt",
  "cache_dir": "cache/envpermit_auto",
  "start_activity": "Confirmation of receipt",
  "attributes_to_ignore": [
    "concept:instance"
  ],
  "rule_discovery_algorithm": "RIPPER",
  "confidence_threshold": 0.5,
  "support_threshold": 0.1,
  "max_rules": 3,
  "k": 2,
  "n_discretize_bins": 20,
  "dl_allowance": 3,
  "prune_size": 0.5,
  "always_force_recompute": true,
  "print_rule_discovery_stats": false,
  "grid_search": false,
  "read_options": {
    "column_names": {
      "Activity": "task",
      "Case ID": "caseid",
      "Resource": "case (responsible)",
      "lifecycle:transition": "event_type"
    },
    "one_timestamp": true
  }
}

=== AutomatedProcessImprovement/knockouts-optimization/knockout_ios/config/bpi_2017_1k_W.json
{
  "$schema": "../../config_schema.json",
  "log_path": "inputs/BPI Challenge 2017_1K_W.xes",
  "output": "./outputs",
  "redesign_results_file_path": "outputs/bpi_2017_1k_W.txt",
  "cache_dir": "cache/bpi_2017_1k_W",
  "start_activity": "A_Create Application",
  "post_knockout_activities": [
    "A_Denied"
  ],
  "exclude_from_ko_activities": [
    "A_Accepted"
  ],
  "rule_discovery_algorithm": "RIPPER",
  "confidence_threshold": 0.5,
  "support_threshold": 0.1,
  "max_rules": 5,
  "k": 2,
  "n_discretize_bins": 20,
  "dl_allowance": 64,
  "prune_size": 0.5,
  "always_force_recompute": false,
  "ignore_log_parsing_cache": false,
  "print_rule_discovery_stats": true,
  "grid_search": false,
  "read_options": {
    "one_timestamp": true
  }
}

=== AutomatedProcessImprovement/knockouts-optimization/knockout_ios/test/config/bpi_2017_W.json
{
  "$schema": "../../../config/config_schema.json",
  "log_path": "test/inputs/BPI Challenge 2017_W.xes",
  "output": "test/outputs",
  "redesign_results_file_path": "test/outputs/bpi_2017_W.txt",
  "cache_dir": "cache/bpi_2017_W",
  "start_activity": "A_Create Application",
  "post_knockout_activities": [
    "A_Denied"
  ],
  "exclude_from_ko_activities": [
    "A_Accepted"
  ],
  "rule_discovery_algorithm": "RIPPER",
  "confidence_threshold": 0.5,
  "support_threshold": 0.1,
  "k": 2,
  "n_discretize_bins": 20,
  "dl_allowance": 64,
  "prune_size": 0.2,
  "always_force_recompute": false,
  "ignore_log_parsing_cache": false,
  "print_rule_discovery_stats": true,
  "grid_search": false,
  "read_options": {
    "one_timestamp": true
  }
}

=== AutomatedProcessImprovement/knockouts-optimization/knockout_ios/config/envpermit.json
{
  "$schema": "../../config_schema.json",
  "log_path": "inputs/Envpermit_complete_cases.xes",
  "output": "./outputs",
  "redesign_results_file_path": "outputs/envpermit.txt",
  "cache_dir": "cache/envpermit",
  "start_activity": "Confirmation of receipt",
  "known_ko_activities": [
    "T02 Check confirmation of receipt",
    "T06 Determine necessity of stop advice",
    "T10 Determine necessity to stop indication"
  ],
  "attributes_to_ignore": [
    "concept:instance",
    "user"
  ],
  "rule_discovery_algorithm": "RIPPER",
  "confidence_threshold": 0.5,
  "support_threshold": 0.1,
  "k": 2,
  "n_discretize_bins": 20,
  "dl_allowance": 64,
  "prune_size": 0.001,
  "always_force_recompute": true,
  "ignore_log_parsing_cache": false,
  "print_rule_discovery_stats": false,
  "read_options": {
    "column_names": {
      "Activity": "task",
      "Case ID": "caseid",
      "Resource": "case (responsible)",
      "lifecycle:transition": "event_type"
    },
    "one_timestamp": true
  }
}
